/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 shoeDraco.gltf --transform
Author: Andreal3ast (https://sketchfab.com/Andreal3ast)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/n43079602v-white-shoe-v6-8056a529c8f5465eb7576da0d8185896
Title: N43079602V_white shoe_v6
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function ShoeDraco(props) {
  const { nodes, materials } = useGLTF('/shoeDraco-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.91}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh material-color="Red" geometry={nodes.polySurface27_Material001_0.geometry} material={materials['Material.001']} position={[0, 0, -0.18]} />
          <mesh material-color="Red" geometry={nodes.polySurface45_lambert6_0.geometry} material={materials.lambert6} />
          <mesh material-color="Red" geometry={nodes.polySurface46_lambert12_0.geometry} material={materials.lambert12} />
          <mesh material-color="Red" geometry={nodes.Cap_Geo_lambert13_0.geometry} material={materials.lambert13} />
          <mesh material-color="Red" geometry={nodes.polySurface31_lambert9_0.geometry} material={materials.lambert9} />
          <mesh material-color="Red" geometry={nodes.polySurface38_lambert11_0.geometry} material={materials.lambert11} />
          <mesh material-color="Red" geometry={nodes.pCube8_lambert14_0.geometry} material={materials.lambert14} />
          <mesh  geometry={nodes.polySurface43_inner_body_and_lays001_0.geometry} material={materials['inner_body_and_lays.001']} />
          <mesh material-color="Red" geometry={nodes.pCube9_Material001_0.geometry} material={materials['Material.001']} />
          <mesh  geometry={nodes.polySurface30_lambert3_0.geometry} material={materials.lambert3} />
          <mesh  geometry={nodes.pTorus18_inner_body_and_lays001_0.geometry} material={materials['inner_body_and_lays.001']} />
          <mesh  geometry={nodes.polySurface14_lambert4_0.geometry} material={materials.lambert4} />
          <mesh  geometry={nodes.polySurface28_bottom_body003_0.geometry} material={materials['bottom_body.003']} />
          <mesh  geometry={nodes.polySurface35_lambert10_0.geometry} material={materials.lambert10} />
          <mesh  geometry={nodes.polySurface44_lambert15_0.geometry} material={materials.lambert15} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/shoeDraco-transformed.glb')
