/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 websiteDraco.gltf --transform
Author: Uğur Yakışık (https://sketchfab.com/UgurYksk)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/laptop-c1988d0aa23544c683adfe53c3cec0c0
Title: laptop
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function WebsiteDraco(props) {
  const { nodes, materials } = useGLTF('websiteDraco-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.93, 0, -0.31]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Material} />
      </group>
      <mesh geometry={nodes.Object_7.geometry} material={materials['Material.001']} position={[0, 0.13, 0]} />
      <mesh geometry={nodes.Object_9.geometry} material={materials['Material.005']} position={[0, 1.41, -1.34]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('websiteDraco-transformed.glb')
